### ISSUE TITLE
Ban-module including timebans

### ISSUE THREAD

**Issue by mastorm** [mastorm/MODiX#5]
As for now, there is a ban module, but it doesnt support timed bans yet. I dont want to do a dirty "I kick you everytime you join until its 12 o clock" ban. It should use the native discord API to do a real ban, then unban later. I dont want to store timestamps in memory for obvious reasons and i dont want to check the Ban-DbCollection every second. Something persistent like akavache or a persistent redis store maybe?

**Comment by formlesstree4** [comment]
An implementation suggestion based on a discussion on the Discord server:

The actual data for this can be backed by MongoDb. An example class for how this data is stored can look something like this:

```csharp
public class TimedBanData
{
   public ulong UserId { get; set; }
   public ulong ServerId { get; set; }
   public DateTime DateBanned { get; set; }
   public TimeSpan Duration { get; set; }
}
```
Whatever class we have would monitor these in memory (loading them back up if the bot went down from Mongo), checking every so often (once a second, every few seconds, doesn't matter) and when a ban duration expires, it unbans the user ID on the server ID (Discord API). Once the ban is confirmed removed, then, it will delete the entry from Mongo and its in memory representation.

How does that sound?
